# Generated by Django 3.1.2 on 2020-12-20 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('cost', models.IntegerField(default='0')),
                ('deposit', models.IntegerField(default='0')),
                ('trading_code', models.IntegerField(unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'reservation_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reserv', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='booking.reservation')),
                ('title', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=1)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
    ]
