# Generated by Django 3.1.2 on 2020-11-06 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(db_column='date-from')),
                ('date_to', models.DateField(db_column='date-to')),
                ('cost', models.IntegerField(default='0')),
                ('deposit', models.IntegerField(default='0')),
                ('trading_code', models.IntegerField(db_column='tradingCode', unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'reservation_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reservation_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='booking.reservation')),
                ('title', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=1)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
    ]
