# Generated by Django 3.1.2 on 2020-11-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=15)),
                ('phone', models.IntegerField()),
                ('manager_id', models.IntegerField(db_column='managerID')),
            ],
            options={
                'db_table': 'hotels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(db_column='roomType', max_length=1)),
                ('quantity', models.IntegerField(default='0')),
                ('img', models.CharField(blank=True, db_column='rImg', max_length=50, null=True)),
                ('price', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
    ]
