# Generated by Django 3.1.2 on 2020-12-20 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images')),
            ],
            options={
                'db_table': 'image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('room_type', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('price', models.IntegerField(default='0')),
                ('description', models.TextField()),
                ('num_people', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('family', 'Family')], max_length=10)),
                ('area', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'room_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=15)),
                ('phone', models.IntegerField()),
                ('manager_id', models.IntegerField(db_column='managerID')),
            ],
            options={
                'db_table': 'hotels',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('available', 'available'), ('using', 'using'), ('need clean', 'need clean'), ('boken', 'broken')], default='available', max_length=32)),
                ('room_type', models.ForeignKey(db_column='room_type', on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.roomtype')),
            ],
            options={
                'db_table': 'room',
            },
        ),
    ]
